assignment-7: src/rectangle.h File Reference
rectangle.h File Reference
#include "point.h"
#include "circle.h"
Data Structures
struct Rectangle
Typedefs
typedef struct Rectangle Rectangle
Functions
Rectangle * createRectangle (Point *p, const double w, const double h)
Rectangle * getBoundingBox (Circle *c)
Typedef Documentation
Rectangle
typedef struct Rectangle Rectangle
Define and typedef a struct Rectangle that contains a Point variable origin that is the top left corner of the rectangle, and two double variables width and height.
Function Documentation
createRectangle()
Rectangle* createRectangle (Point * p, const double w, const double h)
Dynamically allocate and initialize a rectangle.
Parameters
p rectangle's origin point
w rectangle's width
h rectangle's height
Returns
a pointer to a Rectangle
Definition at line 23 of file rectangle.c.
References Rectangle::height, Rectangle::origin, and Rectangle::width.
Referenced by getBoundingBox().
getBoundingBox()
Rectangle* getBoundingBox (Circle * c)
Sets the fields of Rectangle to the bounding box that encloses the circle.
Parameters
c pointer to an input parameter Circle
Returns
a pointer to the circle's bounding box.
Definition at line 39 of file rectangle.c.
References Circle::center, createPoint(), createRectangle(), Circle::radius, Point::x, and Point::y.