assignment-8: src/issn.c File Reference
issn.c File Reference
#include "issn.h"
Functions
char * issnToString (Issn issn, char issnChars [])
Issn parseIssn (const char issnChars [])
Variables
const Issn ISSN_UNKNOWN = 0
Function Documentation
issnToString()
char* issnToString (Issn issn, char issnChars[])
Get string representation of ISSN
Parameters
issn the ISSN value
issnChars array to receive the ISSN characters (OUT)
Returns
pointer to ISSN chars
Definition at line 22 of file issn.c.
Referenced by printJournal(), and test_issn().
parseIssn()
Issn parseIssn (const char issnChars[])
Parse a string representation of an Issn
Parameters
issnChars array with the input Issn string
Returns
the Issn or ISSN_UNKNOWN if string not valid Issn string
Definition at line 33 of file issn.c.
References ISSN_UNKNOWN.
Referenced by test_issn().
Variable Documentation
ISSN_UNKNOWN
const Issn ISSN_UNKNOWN = 0
Sentinel value used when the ISSN is unknown
Definition at line 14 of file issn.c.
Referenced by parseIssn(), and test_issn().