assignment-8: src/journal.h File Reference
journal.h File Reference
#include "issn.h"
#include "publisher.h"
Data Structures
struct Journal
Typedefs
typedef struct Journal Journal
Functions
void printJournal (const Journal *journal)
Journal * createJournal (Issn issn, const char *name, Publisher *pub, Journal *journal)
Journal * getJournalByIssn (Issn issn)
Typedef Documentation
Journal
typedef struct Journal Journal
Struct that defines a Journal
Function Documentation
createJournal()
Journal* createJournal (Issn issn, const char * name, Publisher * pub, Journal * journal)
Create a journal from its information
Parameters
issn the journal Issn
name the journal name
pub the Publisher
journal pointer to space for returned Journal, or NULL to use saved journals array
Returns
pointer to journal struct, or to saved journal if journal is NULL (NULL if not defined)
Definition at line 51 of file journal.c.
References initJournalsCache(), Journal::issn, JOURNALS_SIZE, Journal::name, and Journal::publisher.
Referenced by test_journal_dynamic(), and test_journal_local().
getJournalByIssn()
Journal* getJournalByIssn (Issn issn)
Get a journal from its issn from the journals cache
Parameters
issn the journal Issn
Returns
pointer to saved journal (NULL if not in journals array)
Get a journal from its issn from the journals array
Parameters
issn the journal Issn
Returns
pointer to saved journal (NULL if not in journals array)
Definition at line 86 of file journal.c.
References initJournalsCache().
Referenced by test_journal_dynamic().
printJournal()
void printJournal (const Journal * journal)
Print a Journal
Parameters
journal the journal to print
Definition at line 34 of file journal.c.
References Journal::issn, issnToString(), Journal::name, printPublisher(), and Journal::publisher.