assignment-8: src/journal.c File Reference
journal.c File Reference
#include "journal.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
Functions
static void initJournalsCache (void)
void printJournal (const Journal *journal)
Journal * createJournal (Issn issn, const char *name, Publisher *pub, Journal *journal)
Journal * getJournalByIssn (Issn issn)
Variables
static size_t JOURNALS_SIZE = 0
static Journal ** journals = NULL
Function Documentation
createJournal()
Journal* createJournal (Issn issn, const char * name, Publisher * pub, Journal * journal)
Create a journal from its information
Parameters
issn the journal Issn
name the journal name
pub the Publisher
journal pointer to space for returned Journal, or NULL to use saved journals array
Returns
pointer to journal struct, or to saved journal if journal is NULL (NULL if not defined)
Definition at line 51 of file journal.c.
References initJournalsCache(), Journal::issn, JOURNALS_SIZE, Journal::name, and Journal::publisher.
Referenced by test_journal_dynamic(), and test_journal_local().
getJournalByIssn()
Journal* getJournalByIssn (Issn issn)
Get a journal from its issn from the journals array
Parameters
issn the journal Issn
Returns
pointer to saved journal (NULL if not in journals array)
Definition at line 86 of file journal.c.
References initJournalsCache().
Referenced by test_journal_dynamic().
initJournalsCache()
static void initJournalsCache (void) static
Initialize journals cache. Call from operations that access it
Definition at line 22 of file journal.c.
References JOURNALS_SIZE.
Referenced by createJournal(), and getJournalByIssn().
printJournal()
void printJournal (const Journal * journal)
Print a Journal
Parameters
journal the journal to print
Definition at line 34 of file journal.c.
References Journal::issn, issnToString(), Journal::name, printPublisher(), and Journal::publisher.
Variable Documentation
journals
Journal** journals = NULL static
pointer to allocated journals pointer array
Definition at line 19 of file journal.c.
JOURNALS_SIZE
size_t JOURNALS_SIZE = 0 static
Size of allocated journals pointer array
Definition at line 16 of file journal.c.
Referenced by createJournal(), and initJournalsCache().