assignment-8: src/main_v1.c File Reference
main_v1.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include "journal.h"
#include "CUnit/CUnit.h"
#include "CUnit/Basic.h"
Functions
static void test_issn (void)
static void test_publisher_local (void)
static void test_publisher_dynamic (void)
static void test_journal_local (void)
static void test_journal_dynamic (void)
static CU_ErrorCode test_all_local (void)
int main (void)
Function Documentation
main()
int main (void)
Main program to invoke test functions
Returns
the exit status of the unit tests
Definition at line 217 of file main_v1.c.
References test_all_local().
test_all_local()
static CU_ErrorCode test_all_local (void) static
Unit test driver
Returns
test error code
Definition at line 186 of file main_v1.c.
References test_issn(), test_journal_dynamic(), test_journal_local(), test_publisher_dynamic(), and test_publisher_local().
Referenced by main().
test_issn()
static void test_issn (void) static
Test Issn functions.
Definition at line 19 of file main_v1.c.
References ISSN_UNKNOWN, issnToString(), and parseIssn().
Referenced by test_all_local().
test_journal_dynamic()
static void test_journal_dynamic (void) static
Test Journal functions for dynamic allocation
Definition at line 143 of file main_v1.c.
References createJournal(), createPublisher(), getJournalByIssn(), Journal::issn, Journal::name, and Journal::publisher.
Referenced by test_all_local().
test_journal_local()
static void test_journal_local (void) static
Test Journal functions for local allocation
Definition at line 104 of file main_v1.c.
References createJournal(), createPublisher(), Journal::issn, Journal::name, and Journal::publisher.
Referenced by test_all_local().
test_publisher_dynamic()
static void test_publisher_dynamic (void) static
Test Publisher functions for dynamic allocation.
Definition at line 81 of file main_v1.c.
References createPublisher(), and Publisher::name.
Referenced by test_all_local().
test_publisher_local()
static void test_publisher_local (void) static
Test Publisher functions for local allocation.
Definition at line 53 of file main_v1.c.
References createPublisher(), and Publisher::name.
Referenced by test_all_local().