assignment-8: src/publisher.c File Reference
publisher.c File Reference
#include "publisher.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
Functions
static void initPublishersCache (void)
void printPublisher (const Publisher *publisher)
Publisher * createPublisher (const char *name, Publisher *pub)
Publisher * getPublisherByName (const char *name)
Variables
static size_t PUBLISHERS_SIZE = 0
static Publisher ** publishers = NULL
Function Documentation
createPublisher()
Publisher* createPublisher (const char * name, Publisher * pub)
Get a Publisher by its name
Parameters
name the publisher name
pub pointer to space for returned Publisher, or NULL to use saved publishers array
Returns
pointer to pub struct, or to saved publisher if pub is NULL (NULL if could not save new publisher to publishers array)
Definition at line 44 of file publisher.c.
References initPublishersCache(), Publisher::name, and PUBLISHERS_SIZE.
Referenced by test_journal_dynamic(), test_journal_local(), test_publisher_dynamic(), and test_publisher_local().
getPublisherByName()
Publisher* getPublisherByName (const char * name)
Get a publisher in the publisher cache by name
Parameters
name the name of the publisher
Returns
the Publisher or NULL if not in cache
Definition at line 75 of file publisher.c.
References initPublishersCache().
initPublishersCache()
static void initPublishersCache (void) static
Initialize publishers cache. Call from operations that access it
Definition at line 21 of file publisher.c.
References PUBLISHERS_SIZE.
Referenced by createPublisher(), and getPublisherByName().
printPublisher()
void printPublisher (const Publisher * publisher)
Print a Publisher
Parameters
publisher the publisherto print
Definition at line 33 of file publisher.c.
References Publisher::name.
Referenced by printJournal().
Variable Documentation
publishers
Publisher** publishers = NULL static
pointer to allocated publisher pointer array
Definition at line 18 of file publisher.c.
PUBLISHERS_SIZE
size_t PUBLISHERS_SIZE = 0 static
size of allocated publisher pointer array
Definition at line 15 of file publisher.c.
Referenced by createPublisher(), and initPublishersCache().