assignment-8: test/src/publisher_test.c File Reference
publisher_test.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include "publisher.h"
#include "CUnit/CUnit.h"
#include "CUnit/Basic.h"
Functions
static void test_publisher_local (void)
static void test_publisher_dynamic (void)
void publisher_test (void)
Function Documentation
publisher_test()
void publisher_test (void)
Add suite for publisher unit tests
Definition at line 70 of file publisher_test.c.
References test_publisher_dynamic(), and test_publisher_local().
Referenced by test_all().
test_publisher_dynamic()
static void test_publisher_dynamic (void) static
Test Publisher functions for dynamic allocation.
Definition at line 47 of file publisher_test.c.
References createPublisher(), and Publisher::name.
Referenced by publisher_test().
test_publisher_local()
static void test_publisher_local (void) static
Test Publisher functions for local allocation.
Definition at line 19 of file publisher_test.c.
References createPublisher(), and Publisher::name.
Referenced by publisher_test().